### ISSUE TITLE
Visual Studio for Mac is not opening

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#4772] opened 2018-05-11 00:29 UTC
I changed from alpha to *stable channel* and now VSforMac is not opening.

Installing from the web installer does not work either.

Full log:
https://gist.github.com/netonjm/4663753146f50d946c56158fa81677ca

`rm -rf ~/Library/Caches/VisualStudio` fixed my issue

**Comment by Therzok** [comment] 2018-05-11 09:33
https://devdiv.visualstudio.com/DevDiv/Xamarin%20VS%20for%20Mac/_queries/edit/608547/?triage=true

**Comment by DavidKarlas** [comment] 2018-05-17 11:12
I'm closing this since it's duplicate of VSTS work item Marius mentioned.

**Closed by DavidKarlas** 2018-05-17 11:12 UTC
