### ISSUE TITLE
Having custom widgets GTK# in MonoDevelop 7.4 breaks my solution

### ISSUE THREAD

**Issue by define-private-public** [mono/monodevelop#4100] opened 2018-03-09 02:14 UTC
Before I was using MonoDevelop 5.x on Ubuntu Linux (17.10), then I updated to the latest IDE that's on the the repo listed here: http://www.monodevelop.com/download/

I've got solution (or series of projects) that use GTK# (2.12) that won't compile.  This caused by this snippet of code found in `generated.cs` for each custom widget that I've made using the GUI builder:
```
		private void OnSizeRequested(object sender, Gtk.SizeRequestedArgs args)
		{
			if ((this.child != null))
			{
				args.Requisition = this.child.SizeRequest();
			}
		}
```

The culprit is the `Gtk.SizeRequestedArgs`.  It says that it can't find it and asks if I forgot to include an assembly reference.  I tested this by creating a fresh GTK# 2 project and the same thing happened.

BTW, when creating a brand new GTK# 2 project, the GTK version isn't set to 2.12 by default (or 3.0).  It's set to nothing in the project settings.  You might want to fix that too.

> VS bug [#584829](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584829)

**Comment by terrak** [comment] 2018-03-16 09:26
I have the same problem (Debian 9.4 : deb https://download.mono-project.com/repo/debian stretch main). 
Please, a correction is requested urgently.

**Comment by define-private-public** [comment] 2018-03-16 12:29
I want to note that I was able to get my solution back in a working state, but I did have to downgrade MonoDevelop to what was still in the Canonical/Ubuntu repos, and it also took a few extra steps of manual cleaning, and I think messing with a reference or two in the Project files.

**Comment by splatpope** [comment] 2018-12-26 23:03
I'm having the exact same problem.

The weirdest thing is that the problem appeared out of nowhere, I was able to build my project successfully and for some reason, shit started hitting the fan overnight.

I would love to disable the GUI designer altogether, but I have no idea how to do so and I'd rather find out what the hell is causing monodevelop to choke on this specific class.

@define-private-public , could you please describe the "few extra steps of manual cleaning" you had to perform ?

**Comment by splatpope** [comment] 2018-12-27 00:06
WELL it seems the problem was mainly caused by a custom widget that I had deleted, for some reason there was a file in the UI tab of the solution explorer which should have been deleted but wasn't.

Either that or reinstalling gtk-sharp3 did the trick.

Interestingly, I can now build without problem, using code from both versions of gtksharp even though it's set to use 2.12.

This stuff is driving me crazy.

**Comment by Therzok** [comment] 2018-12-27 12:46
I can't seem to reproduce this locally. Can you please attach the log files of a crashing session?

https://www.monodevelop.com/developers/articles/user-profiles/#logs

**Comment by splatpope** [comment] 2018-12-27 14:40
No can do, I had deleted the whole cache folder thinking it would help, but it's solved for me now anyways.

**Comment by Therzok** [comment] 2019-10-12 02:42
Closing, not actionable.

**Closed by Therzok** 2019-10-12 02:42 UTC
Labels: vs-sync
