### ISSUE TITLE
Frequent random crashes (with F# bindings installed)

### ISSUE THREAD

**Issue by jwosty** [mono/monodevelop#4411] opened 2018-04-02 17:25 UTC
I haven't been able to pinpoint an exact cause, but VS for Mac has started frequently crashing for me (a few times a day right now), at seemingly random times. Looking at the stacktrace, it seems like it might be related to the F# binding, though I haven't been opening any C# solutions recently, so I don't know. I believe this has coincided with a recent update, but I'm not sure. It didn't do this at all until less than a week ago.

[Here is a full log from the latest crash](https://gist.github.com/jwosty/a4240b7a813d023ffa6fccef4ea1384c)

Additionally, not sure if related (otherwise it's out of the scope of this issue), but F# intellisense has been totally wonky for me for a long time, even after total reinstalls of the IDE. So maybe there's just something wrong with my box? Help would be appreciated -- VS for Mac is extremely unusable for me with these factors combined :)

> VS bug [#593854](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/593854)

**Comment by nosami** [comment] 2018-04-03 10:50
Looks to be a dupe of https://github.com/mono/monodevelop/issues/4351

**Comment by nosami** [comment] 2018-04-04 18:24
This is fixed in the next 7.4 service release. The intellisense issue is being tracked by other tickets.

Thanks for reporting!

**Closed by nosami** 2018-04-04 18:24 UTC
Labels: Area: F#, vs-sync

**Comment by xamarin-release-manager** [comment] 2020-01-22 13:48
> [sync] [VS-12] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Pull Request #4416 merged by: Jason Imison  
 Author: mono  
 Commit: 5063d19709d8b719a3019892c7f923acda870cfb (xamarin/monodevelop)
