### ISSUE TITLE
NullRef in UpdateService.cs:582

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5996] opened 2018-09-17 21:49 UTC
VSMac 7.6.5.20

```
ERROR [2018-09-16 19:26:30Z]: Updater token could not be retrieved
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Ide.Updater.UpdateService+<GetDefaultUserToken>d__61.MoveNext () [0x00019] in /Users/vsts/agent/2.140.0/work/1/s/md-addins/Xamarin.Ide/Xamarin.Ide/Xamarin.Ide.Updater/UpdateService.cs:582 

```

> VS bug [#685791](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685791)

**Comment by Therzok** [comment] 2018-09-18 07:28
cc @nosami

**Comment by nosami** [comment] 2018-12-06 09:03
Dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740202

**Closed by nosami** 2018-12-06 09:03 UTC
Labels: Area: Updater, vs-sync
