### ISSUE TITLE
Error in updating folding accessibility

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#6446] opened 2018-10-23 15:42 UTC
From UI tests:
```
ERROR[2018-10-23 11:29:17Z]: An unhandled exception has occurred. Terminating Visual Studio? False
System.NullReferenceException: Object reference not set to an instance of an object
  at Mono.TextEditor.FoldMarkerMargin.UpdateAccessibilityTimer () [0x00070] in /Users/vsts/agent/2.140.2/work/1/s/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs:194 
  at GLib.Timeout+TimeoutProxy.HandlerInternal (System.IntPtr data) [0x00017] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/gtk-sharp-None/glib/Timeout.cs:38 
```

> VS bug [#713030](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713030)

**Comment by mrward** [comment] 2018-10-23 16:43
This is a dupe of #6282

**Closed by mrward** 2018-10-23 16:43 UTC
Labels: Area: General, vs-sync
