### ISSUE TITLE
Types are not loading and intellisense is broken sometimes in SourceEditor

### ISSUE THREAD

**Issue by netonjm** [mono/monodevelop#3684] opened 2018-01-18 09:14 UTC
It's not happening allways, but sometimes opening MonoDevelop solution, the editor don't resolve types and intellisense stop work.

<img width="1656" alt="2018-01-18_1016" src="https://user-images.githubusercontent.com/1587480/35090037-ce0f1c2e-fc38-11e7-86fa-dfe843cbd9a7.png">

This is the Ide.log:

[Ide.2018-01-18__09-27-13.log](https://github.com/mono/monodevelop/files/1642217/Ide.2018-01-18__09-27-13.log)

Visual Studio Enterprise 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 839)
Installation UUID: ac2f5f5a-65c6-4e02-aae1-61d2ac9aabc1
Runtime:
	Mono 5.8.0.103 (2017-10/1359c52fc6e) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000103

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.1
	1.0.5
	1.0.4
	1.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview2-003156
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Users/jmedrano/Projects/profiler/src/XamarinProfiler.Mac/bin/Debug/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.2.0.1 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.8.0.1 (Visual Studio Enterprise)
Hash: 82e38cd1
Branch: d15-6
Build date: 2017-12-22 14:23:52-0500

Xamarin.Android
Version: 8.2.0.1 (Visual Studio Enterprise)
Android SDK: /Users/jmedrano/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0-beta1+69
Hash: 4012b4e
Branch: master
Build date: Thu, 07 Dec 2017 16:20:26 GMT
Client compatibility: 1

Build Information
Release ID: 704000839
Git revision: 82eabac6f9ebeaa9c0f3143baa8037c26c6c00fc
Build date: 2018-01-05 22:22:29-05
Xamarin addins: b2cfc17e56386f2c360aaa8b02404b900d6be8c1
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

> VS bug #571170

**Comment by cwensley** [comment] 2018-01-18 17:28
This happens to me a _lot_ too, so let me know if I can help!  At least for me it seems to be related to having multiple projects reference the same files, but I have no idea if that is the cause.

**Comment by Therzok** [comment] 2018-01-18 17:42
Seems like project reload is not signalling roslyn properly. Will take a look.

**Comment by rodrmoya** [comment] 2018-01-24 11:24
This happens also to me when switching branches on a terminal several times. After a few branch switches (not sure how many), types are not resolved and intellisense stops working

**Comment by Therzok** [comment] 2018-01-30 13:08
https://github.com/dotnet/roslyn/pull/24458

Probably related

**Comment by Therzok** [comment] 2018-03-13 20:36
Should be fixed via:
https://github.com/mono/monodevelop/pull/4010
https://github.com/mono/monodevelop/pull/4023
https://github.com/mono/monodevelop/pull/4024

Please re-open if you are still seeing the issue.

**Closed** 2018-03-13 20:36 UTC
Labels: vs-sync

**Comment by netonjm** [comment] 2018-03-14 16:44
I will do :)
