### ISSUE TITLE
Text does not indent on pressing return for new method

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5406] opened 2018-07-13 14:49 UTC
VS Mac 7.5.0.593
Release ID: 707000593
Git revision: 3e446326d8de8d6cd19c44261fd4003bc96ccf46
Build date: 2018-07-12 08:46:03+00
Build branch: master-mk-refatcoringchanges
Xamarin extensions: 240be06f54a86de12cf9e861cab9c06c358ff97c

Not sure if this related to #5401 or not. Not tried a build with the fix for 5401.

Creating a new method, typing in the opening curly brace, and then pressing return does not indent the line. Pressing return again and the next line is indented as expected.

![newmethodindentation](https://user-images.githubusercontent.com/372361/42697833-1ff018c6-86b4-11e8-8bd4-a0e81d80c1e5.gif)

> VS bug [#647612](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/647612)

**Comment by mkrueger** [comment] 2018-07-16 06:33
I think it is related should be fixed - at least it works for me.

**Comment by mkrueger** [comment] 2018-07-16 07:17
Closing as duplicate of  #5401 (even if not 100% correct but the fix is the same).

**Closed by mkrueger** 2018-07-16 07:17 UTC
Labels: Area: Text Editor, vs-sync
