### ISSUE TITLE
Error Tooltips don't close

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4976] opened 2018-06-01 04:31 UTC
![tooltipsdontclose](https://user-images.githubusercontent.com/679326/40821136-e061ee84-6519-11e8-848c-90818c90a93b.gif)

This is on latest master. @mkrueger Any idea what could it be? Language tooltips and keyword tooltips seem to be closing normally.

In general we're seeing quite a lot of strangeness with tooltips nowadays.

> VS bug [#624915](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624915)

**Comment by KirillOsenkov** [comment] 2018-06-01 04:50
Reproduces on Mac as well.

**Comment by Therzok** [comment] 2018-06-01 04:57
cc @DavidKarlas

**Comment by nosami** [comment] 2018-06-01 06:02
Looks like a dupe of #4972

**Comment by slluis** [comment] 2018-06-01 07:15
Closing since it is a duplicate.

**Closed by slluis** 2018-06-01 07:15 UTC
Labels: Area: Text Editor, vs-sync
