### ISSUE TITLE
Workspaces are re-created every time any solution is opened

### ISSUE THREAD

**Issue by NTaylorMullen** [mono/monodevelop#3517] opened 2017-12-19 18:26 UTC
I’m seeing that a new Workspace is created and exposed via TypeSystemService.Workspace every time you close/re-open a solution.  This prevents users from attaching to the Workspace (either by services, or attaching to workspace events) to manage any kind of state. For instance, the WorkspaceChanged event is used to track project/solution changes so services can react accordingly.

Roslyn’s APIs expose the contract of the solution changing for a workspace, including events about the open/close lifecycle; it also has its own services concept Workspace.Services which expect to be long-live. Visual Studio for windows uses Roslyn’s Workspace type this way so it worries me that MonoDevelops current approach of re-creating workspaces would result in additional pain points in the future for anyone porting code.

**Comment by mhutch** [comment] 2017-12-22 03:38
cc @KirillOsenkov

**Comment by Therzok** [comment] 2018-01-03 15:48
cc @mkrueger

**Comment by mkrueger** [comment] 2018-01-10 07:40
Not a bug or issue IMO. A Workspace is for me the representation of the solution. That ensures that we don't leak any memory via workspaces.

Workspaces work differently in MD alone because of the possibility to load more that one solution so code needs to handle that anyways.

**Comment by NTaylorMullen** [comment] 2018-01-10 18:05
Few questions then.

1. Is there an event that notifies when new workspaces get added/removed?
2. For singleton MEF services that have the lifecycle of monodevelop.exe do you expect every one of those services to listen to these added/removed events and update their workspaces? In VS windows a common pattern was to take in the current workspace, save it in a field, attach events to it and then read from it or react to it later. Seems super heavy to add that expectation to every component that needs the workspace.
3. What's the expectation for all VS for mac code that's being ported? There being 1 workspace that's mutated is an expectation that lots of VS windows code depends on. I guess every piece will have to react to this?

/cc @jasonmalinowski @rynowak

**Comment by KirillOsenkov** [comment] 2018-01-10 18:47
cc @dustincampbell in case he has any thoughts.

MonoDevelop can open more than one solution at a time (potentially rewiring References to be ProjectReferences across solutions).

Roslyn's philosophy has always been that the main workspace lives for the lifetime of an application, and is reused as solutions are opened/closed. However this was never designed with the multiple side-by-side solutions in mind.

Our options are:

 1. global static events such as WorkspaceAdded/WorkspaceRemoved on TypeSystemService, that workspace consumers subscribe to and when a workspace is added, they attach and do all initialization. The downside here is that we need to ensure that consumers subscribe before the workspace is added (rendezvous problem). Maybe export subscribers using MEF or collect event subscribers using Mono.Addins?
 2. Have a single primary workspace and when solutions get opened/closed just add/remove all projects to the same workspace. I feel like this model would be more natural to Roslyn and all existing consumers. The argument about potential memory leaks is strange. If there's a leak we'll need to investigate and fix, a fear of leaks shouldn't be a factor in design decisions.

Also cc @DavidKarlas FYI

**Comment by mhutch** [comment] 2018-01-10 19:47
What issues might arise from having multiple solutions' projects in the same workspace?

**Comment by KirillOsenkov** [comment] 2018-01-10 19:56
I'd say it's worth prototyping to find out. I could try and look into this.

**Comment by slluis** [comment] 2018-01-10 21:11
> 1. Is there an event that notifies when new workspaces get added/removed?

There are events that are fired when solutions are loaded/unloaded (`IdeApp.Workspace.WorkspaceItemLoaded/Unloaded`), so that's when workspaces are added/removed.

> 2. For singleton MEF services that have the lifecycle of monodevelop.exe do you expect
> every one of those services to listen to these added/removed events and update 
> their workspaces? In VS windows a common pattern was to take in the current workspace,
> save it in a field, attach events to it and then read from it or react to it later. Seems super
> heavy to add that expectation to every component that needs the workspace.

Every VS for Mac extension needs to take into account that the IDE can load more than one solution at once. The `IdeApp.Workspace` object is a "meta" workspace that provides some high level project model events, and more events can be subscribed on the project model itself. VS for Mac extensions currently use those events, not Roslyn workspace events.

> 3. What's the expectation for all VS for mac code that's being ported? There being 1
> workspace that's "mutated" is an expectation that lots of VS windows code depends
> on. I guess every piece will have to react to this?

Right now that code will have to consider multiple workspace, yes. If multiple solution support is added to roslyn, then we can simplify things, but even in that case extensions will still have to take into account that a workspace can contain more than one solution.

**Comment by slluis** [comment] 2018-01-10 21:16
> What issues might arise from having multiple solutions' projects in the same workspace?

This might fix some cases, but I think it would just exchange a set of problems by another set of problems, since it breaks the expectation in existing code that all projects in a workspace belong to one solution.

**Comment by mhutch** [comment] 2018-01-11 22:09
@slluis how much does that expectation matter though? Will changing it actually cause any problems?

As Kirill pointed out, putting all the projects in one workspace means we can do neat/useful things such as implicitly wiring up cross-solution project references by matching dll references to project outputs, which I think would be super useful for the case where users open related solutions side by side. Think monodevelop and md-addins, for example.

**Comment by slluis** [comment] 2018-01-12 11:00
> @slluis how much does that expectation matter though? Will changing it actually cause any problems?

I have no idea. I'm just pointing out that if recreating workspaces breaks expectations of existing VS code (which is the whole point of this discussion), loading projects from different solutions in a single workspace will also break expectations.

**Comment by mhutch** [comment] 2018-01-12 17:27
If nothing depends on it I'd call it an unimportant assumption rather than an expectation :)

**Comment by jasonmalinowski** [comment] 2018-01-12 23:00
> As Kirill pointed out, putting all the projects in one workspace means we can do neat/useful things such as implicitly wiring up cross-solution project references by matching dll references to project outputs, which I think would be super useful for the case where users open related solutions side by side.

I'm always a strong believer that you're using an API right if you have "unexpected surprises", so this would strongly lead me to believe that MonoDevelop should be using one workspace for the multiple solution case because then you can do cross-project references, you can have refactorings or tools like Find References work across them, etc.

If you consider the types of workspaces we have in Visual Studio for Windows, they are:

- VisualStudioWorkspace (cleverly named, the main one that contains your regular projects and source files)
- MiscellaneousFilesWorkspace (no projects, just loose files opened up with no structure)
- InteractiveWindowWorkspace (projects are submission in an interactive window REPL)
- MetadataAsSourceWorkspace (files are generated, projects represent surrounding context to make features work)

Each of these are distinct instances primarily because they represent fundamentally different sources of the concept of "projects" and "documents". Calling TryApplyChanges with a change that wants to add a document in each case does fundamentally different (or impossible!) things because the meaning itself of a "document" is an abstraction over very different things. In the case of multiple solutions being opened, what would force them into separate workspace instances would not because they're "multiple solutions" but rather because you need some fundamentally different behavior. For example, if one was opening local code, and one was opening some code in the cloud with no local enlistment that was being fetched on demand, or every keystroke creates a new commit on GitHub, etc.

> loading projects from different solutions in a single workspace will also break expectations.

If there were any core assumptions in Roslyn that were broken an needed fixing, I would personally support just fixing those. Solution.FilePath is a thing, but it appears the only code in Visual Studio for Windows that inspects it is some persistence service that we could easily move off of that. (I'm already doing some refactorings there as it is to fix other concerns.)

> There being 1 workspace that's "mutated" is an expectation that lots of VS windows code depends on. I guess every piece will have to react to this?

The interesting part is for a vast majority of Roslyn IDE code consuming the workspace layer you tend to not know where workspaces are coming from. Most of Roslyn experiences start with a text buffer, and we simply fetch the workspace associated to that text buffer and operate on that with no caring about where it came from. It's only "ephemeral" features like Go to Type, or maybe the solution explorer, that ever grab "the workspace" without starting from a buffer. Early in Roslyn we did bake in a concept of a "primary workspace" but we quickly regretted it, and figured that for this sort of situation where hosts have different workspace creation like this your best bet is to abstract as much as possible to consume just the "Workspace" type, and then have a thin shim per host as needed to figure out which Workspace type needs to be operated on.

**Comment by KirillOsenkov** [comment] 2018-01-12 23:57
I've filed https://github.com/dotnet/roslyn/issues/24218 to investigate if a change on the Roslyn side would help facilitate this becoming less of a hack. I'm wondering if we can preserve most of the existing workspace API and behavior and allow adding projects from more than one solution at a time, merging them. And when a solution is removed, remove the projects from that solution from the workspace.

**Comment by slluis** [comment] 2018-01-13 15:52
> In the case of multiple solutions being opened, what would force them into separate workspace instances would not because they're "multiple solutions" but rather because you need some fundamentally different behavior.

We don't need a fundamentally different behavior, but we need the workspaces to be isolated from each other because they belong to solutions that may not have any relation between them. For example, let's say there is a VS extension that performs a global refactoring operation on all projects of a solution. If MonoDevelop loads projects from different solutions in a single workspace, the extension is going to break because it will assume that all projects of the workspace belong to the same solution, which would not be true, and it would refactor code where it shouldn't.

There will also be problems with events. After loading a solution into a workspace, how do we load the second one? by adding projects to the open solution? How we can expect extensions to interpret that correctly?

> > loading projects from different solutions in a single workspace will also break expectations.

> If there were any core assumptions in Roslyn that were broken an needed fixing, I would personally support just fixing those

I was referring to expectations done by extensions, not by the Roslyn code itself. The expectation that everything in VisualStudioWorkspace belongs to a single solution. 

> The interesting part is for a vast majority of Roslyn IDE code consuming the workspace layer you tend to not know where workspaces are coming from

Then having one workspace for each open solution should not be such a big problem.

**Comment by jasonmalinowski** [comment] 2018-01-23 04:59
> For example, let's say there is a VS extension that performs a global refactoring operation on all projects of a solution. If MonoDevelop loads projects from different solutions in a single workspace, the extension is going to break because it will assume that all projects of the workspace belong to the same solution.

If the projects are unrelated because they don't have project references between them, it won't even chase to the other projects in the first place. Doing so would already be a bug. We already have customers today who create "uber solutions" of unrelated projects where they'd be broken.

> After loading a solution into a workspace, how do we load the second one? by adding projects to the open solution? How we can expect extensions to interpret that correctly?

It has never been the case that Roslyn in Visual Studio for Windows loads all projects at once. In many cases we load them asynchronously, and add the projects one at a time. Those who write Roslyn extensions are surprised by this, but adding projects "later" is not only expected but actually the common case. If you don't handle this, your Visual Studio for Windows extension atop Roslyn is already broken.

**Comment by mkrueger** [comment] 2018-01-23 10:26
Of course extensions need to handle project load/unloading events in VS4Mac as well. Alone for adding/removing projects from the solution.

However we do not load "the workspace" into a single roslyn workspace - so we've more than one roslyn workspace in general. However all refactoring operations are broken if the solution has common projects.
That's by design - there isn't a way around that IMO and up to the users to sanitize their solution/workspace layout.

I see two ways:

1) Extensions need to be able to handle roslyn workspace loaded/unloaded events
2) We remove the ability to load more than one solution at once.

We should consider 2) as an option because of the breakage of refactoring operations.

Regards
Mike
________________________________
Von: Jason Malinowski <notifications@github.com>
Gesendet: Dienstag, 23. Januar 2018 05:59:33
An: mono/monodevelop
Cc: Mike Krüger; Assign
Betreff: Re: [mono/monodevelop] Workspaces are re-created every time any solution is opened (#3517)


For example, let's say there is a VS extension that performs a global refactoring operation on all projects of a solution. If MonoDevelop loads projects from different solutions in a single workspace, the extension is going to break because it will assume that all projects of the workspace belong to the same solution.

If the projects are unrelated because they don't have project references between them, it won't even chase to the other projects in the first place. Doing so would already be a bug. We already have customers today who create "uber solutions" of unrelated projects where they'd be broken.

After loading a solution into a workspace, how do we load the second one? by adding projects to the open solution? How we can expect extensions to interpret that correctly?

It has never been the case that Roslyn in Visual Studio for Windows loads all projects at once. In many cases we load them asynchronously, and add the projects one at a time. Those who write Roslyn extensions are surprised by this, but adding projects "later" is not only expected but actually the common case. If you don't handle this, your Visual Studio for Windows extension atop Roslyn is already broken.

**Comment by nosami** [comment] 2018-01-23 10:39
> We should consider 2) as an option because of the breakage of refactoring operations.

I hope not. I rely on this hidden(?) feature almost daily. I use it for debugging 3rd party libraries, e.g. F# compiler code from inside MonoDevelop. I load the MonoDevelop source code and the compiler source code as separate solutions.

**Comment by slluis** [comment] 2018-01-23 12:19
> > For example, let's say there is a VS extension that performs a global refactoring operation on all projects of a solution. If MonoDevelop loads projects from different solutions in a single workspace, the extension is going to break because it will assume that all projects of the workspace belong to the same solution.

> If the projects are unrelated because they don't have project references between them, it won't even chase to the other projects in the first place. Doing so would already be a bug. We already have customers today who create "uber solutions" of unrelated projects where they'd be broken.

This is just a possible example of breaking expectations. Another example would be an extension that calculates source code metrics for a solution. My point is that if we put all projects for all solutions in a single workspace, extensions can't perform operations that are supposed to be done only within the bounds of a single solution.

> > After loading a solution into a workspace, how do we load the second one? by adding projects to the open solution? How we can expect extensions to interpret that correctly?

> It has never been the case that Roslyn in Visual Studio for Windows loads all projects at once. In many cases we load them asynchronously, and add the projects one at a time. Those who write Roslyn extensions are surprised by this, but adding projects "later" is not only expected but actually the common case. If you don't handle this, your Visual Studio for Windows extension atop Roslyn is already broken.

Fair enough.

**Comment by slluis** [comment] 2018-02-12 23:50
Closing since we reached an agreement. Extensions can subscribe the solution opened/closed events, and then get the corresponding Workspace from the type service.

**Closed by slluis** 2018-02-12 23:50 UTC
