### ISSUE TITLE
Switching branch outside of IDE does not trigger project reload

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5705] opened 2018-08-17 04:24 UTC
If I switch git branch outside of the IDE, and one or more of the project files change, they are no longer automatically reloaded.

7.7 build 805

> VS bug [#669787](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669787)

**Comment by mrward** [comment] 2018-09-03 10:43
I tried a simple test but could not reproduce the problem with VS Mac 7.7.0.1192.

My test:

1. Simple local git repository - one C# library project.
2. Two branches - test and master - all changes committed.
3. test branch has a modified .csproj (extra reference and one extra .cs file), also MyClass.cs is modified.
4. With the solution open in VS Mac, opening a terminal window and run `git checkout test` or `git checkout master`. Switching back to VS Mac - the project reloads and the MyClass.cs file reloads.

**Comment by mrward** [comment] 2018-09-25 17:28
Modifying a .csproj inside a solution folder does not reload the project. The solution's ItemReloadRequired is not fired in this case.

**Comment by xamarin-release-manager** [comment] 2018-09-27 06:38
> [sync] [VS-18] Comment by **xamarinc**



Fixed in version 7.8.0.576 (master)



Author: Matt Ward  
 Commit: 128a2d5e560ae1d87090a032e82c7263bee2f7b8 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment] 2018-09-27 06:38
> [sync] [VS-19] Comment by **xamarinc**



Fixed in version 7.7.0.1430 (release-7.7)



Pull Request #6082 merged by: Lluis Sanchez  
 Author: mono  
 Commit: 494763318a3e0b452d0efd50aef67e10daaad8f0 (mono/monodevelop)

**Closed by xamarin-release-manager** 2018-09-27 06:38 UTC
Labels: Area: Version Control, high-priority, regression, vs-sync

**Comment by xamarin-release-manager** [comment] 2020-01-22 14:03
> [sync] [VS-36] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: Matt Ward  
 Commit: 128a2d5e560ae1d87090a032e82c7263bee2f7b8 (xamarin/monodevelop)
