### ISSUE TITLE
Unit testing for .NET Core doesn't work in 2019 Preview 2

### ISSUE THREAD

**Issue by usr-sse2** [mono/monodevelop#7092] opened 2019-02-08 11:03 UTC
Steps to reproduce:
```bash
dotnet new nunit                 # or mstest, or xunit – all of them don't work
open Tests.csproj -a "/Applications/Visual Studio (Preview).app"
```
Restore NuGet packages and build the project. The "Unit Tests" panel is either empty or displays an error, clicking "Run All" doesn't run anything.
It worked in 2017 and 2019 Preview 1.

> VS bug [#788442](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788442)

**Comment by rodrmoya** [comment] 2019-02-20 14:27
Just tried with latest master, and everything seems to work for me, so I guess it might be because of the .NET Core version(s) you have installed, so can you please provide:

- output of `dotnet --list-sdks`
- Ide.log after reproducing the error

There was recently a bug with one of the .NET Core 3.0 previews, so I wonder if you have that one installed? Also, we fixed a few bugs that might be related after Preview 2 was released, so might be already fixed in the next preview

**Comment by usr-sse2** [comment] 2019-02-20 14:36
The output of `dotnet --list-sdks`:
```
2.1.500 [/usr/local/share/dotnet/sdk]
2.2.101 [/usr/local/share/dotnet/sdk]
3.0.100-preview-009812 [/usr/local/share/dotnet/sdk]
3.0.100-preview-010184 [/usr/local/share/dotnet/sdk]
```

The project I'm working on is using .NET Core 2.2.

[Ide.log](https://github.com/mono/monodevelop/files/2884993/Ide.log)

**Comment by rodrmoya** [comment] 2019-02-20 14:54
can you try removing the 3.0.100-preview-010184? I think that's the one that was causing several weird errors

**Comment by usr-sse2** [comment] 2019-02-20 15:01
Removed even both 3.0 sdks and the corresponding runtimes, restarted Visual Studio and rebuilt the project – no changes.

**Comment by rodrmoya** [comment] 2019-02-20 15:06
did you re-create the project also?

**Comment by usr-sse2** [comment] 2019-02-20 15:10
Tried to recreate, doesn't help.

**Comment by usr-sse2** [comment] 2019-02-20 17:07
I built `master`, and it works, so it's probably already fixed.

**Comment by rodrmoya** [comment] 2019-02-20 17:18
Good! Closing this one then, thanks!

**Closed by rodrmoya** 2019-02-20 17:18 UTC
Labels: Area: .NET Core, need-info, vs-sync
