### ISSUE TITLE
EditorConfigService freezes UI when creating a new project

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#5508] opened 2018-07-25 06:24 UTC
I dunno how to share any editorconfig stuff in my local PC, but so far here is the repro steps for the issue: launch MD and create a new .NET Console project. It won't complete after you click "Create" button in the last dialog.

.NET Core App is somehow not affected. Xamarin.Android was.

monodevelop master (b9e364f)

While I was debugging monodevelop, I found the actual stopper:

![screenshot from 2018-07-25 15-22-26](https://user-images.githubusercontent.com/53929/43183061-b2272d92-901e-11e8-989e-3cfa2aac6fcd.png)

If I modified that method to return a default empty result regardless of the state, the problem is gone.

> VS bug [#653871](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/653871)

**Comment by mkrueger** [comment] 2018-07-25 07:34
I suppose some template implementation doesn't use the async version SaveFileAsync instead SaveFile.

The async version needs to be used in all implementations. That's why .NET Console works.

**Comment by atsushieno** [comment] 2018-07-25 07:41
.NET Console project does NOT work - .NET **Core** Console project works.

**Comment by mrward** [comment] 2018-07-25 08:05
The problem is that using Task.Result will block the UI thread if something in Roslyn uses Task.Run since the task cannot get back onto the UI thread to continue. https://github.com/mono/monodevelop/issues/5506

**Comment by mrward** [comment] 2018-07-25 08:08
This UI hang should be fixed by 
https://github.com/mono/monodevelop/commit/a332b6e34ad6e04a095a8a0e1128910213db0131

**Comment by mrward** [comment] 2018-07-25 10:01
I had a look at .NET Core projects since I cannot reproduce a UI hang here, the same as @atsushieno. The reason is that the file formatting is done differently with the .NET Core project and the EditorConfigService is not used - whether it should be is a question here.

.NET Core projects use a different templating provider and format the files with:

```
	var content = await TextFileUtility.ReadAllTextAsync (file);
	var formatted = formatter.FormatText (policies, content.Text);
```

Where as console projects using the original templating engine do:

```
	var document = TextEditorFactory.CreateNewReadonlyDocument (new StringTextSource (content), fileName);
	// Avoid possible UI thread deadlock in CSharpFormatter by running the formatter with Task.Run.
	var formatted = await Task.Run (() => formatter.Format (policyParent?.Policies, document));
```

Note the Task.Run was added by me to avoid the UI hang.

Looking at the CSharpFormatter this results in two different parts of the code being used:

```
		protected override ITextSource FormatImplementation (PolicyContainer policyParent, string mimeType, ITextSource input, int startOffset, int length) 
		{
			var chain = DesktopService.GetMimeTypeInheritanceChain (mimeType);
			var policy = policyParent.Get<CSharpFormattingPolicy> (chain);
			var textPolicy = policyParent.Get<TextStylePolicy> (chain);
			var optionSet = policy.CreateOptions (textPolicy);

			if (input is IReadonlyTextDocument doc) {
				try {
					var conventions = EditorConfigService.GetEditorConfigContext (doc.FileName).WaitAndGetResult ();
					if (conventions != null)
						optionSet = new FormattingDocumentOptionSet (optionSet, new CSharpDocumentOptionsProvider.DocumentOptions (optionSet, conventions.CurrentConventions));
				} catch (Exception e) {
					LoggingService.LogError ("Error while loading coding conventions.", e);
				}
			}

			return new StringTextSource (FormatText (optionSet, input.Text, startOffset, startOffset + length));
		}
```

.NET Core projects do not use the EditorConfigService since they do not pass a IReadonlyDocument. .NET console projects do pass an IReadonlyDocument so do call the EditorConfigService.

So it looks to me as though the .NET Core file formatting code is wrong here since it avoids the use of the EditorConfigService and just by luck avoids a possible UI thread hang.

**Comment by mrward** [comment] 2018-07-27 12:23
This should be fixed in latest master.

**Closed by mrward** 2018-07-27 12:23 UTC
Labels: Area: Roslyn Integration, vs-sync
