### ISSUE TITLE
Editorconfig analyzer severity levels have no effect

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4745] opened 2018-05-07 21:37 UTC
Changing analyzer severity levels specified in editorconfig has no effect.

Example:
```
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_for_built_in_types = false:error
csharp_style_var_elsewhere = false:error
```

If I delete the .vs (clearing roslyn caches), the updated severity levels take effect. It looks the cache isn't being invalidated when the editroconfig changes.

> VS bug [#612540](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612540)

**Comment by mhutch** [comment] 2018-06-22 14:16
This hasn't been fixed

**Comment by slluis** [comment] 2018-06-22 14:30
Duplicate of https://developercommunity.visualstudio.com/content/problem/268235/editorconfig-doesnt-work-for-vs-for-mac-using-net.html.

**Closed by slluis** 2018-06-22 14:30 UTC
Labels: Area: Roslyn Integration, vs-sync
