### ISSUE TITLE
Structured log warning icon is not eligible when selected

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#5007] opened 2018-06-05 19:18 UTC
<img width="1432" alt="screen shot 2018-06-05 at 12 15 42" src="https://user-images.githubusercontent.com/109974/40997718-7439b008-68ba-11e8-8cfe-d1aa7a09f5dd.png">

> VS bug [#629164](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/629164)

**Comment by Therzok** [comment] 2018-06-05 20:37
cc @rodrmoya

**Comment by rodrmoya** [comment] 2018-06-06 19:13
cc @vancura

**Comment by maryanne-exe** [comment] 2018-06-14 23:38
could you please elaborate what is the problem with warning icon here? @Therzok

**Comment by Therzok** [comment] 2018-06-15 07:35
@maryanne-exe it looks like a chevron pointing upwards, see how most chevrons are on the left side and it has almost the same color.

The icon should probably have a different color when selected

**Comment by vancura** [comment] 2018-06-15 10:56
@maryanne-exe: I thought we'd discuss this on Slack, but ok :)

So the problem is that the icon can't contain a glyph in this size (the icon is too small for anything meaningful inside). Mainly seen in this `~sel` icon we need a larger icon for warning (the normal one). I can replace the files, but you should know that we will use larger icons for errors, warnings, and info from now on.

Ping me if this is unclear.

**Comment by maryanne-exe** [comment] 2018-06-21 18:48
I believe it will look too heavy having large icons in errors/warning list; it was the reason why we switched to small ones.
As we discussed with @vancura on Slack, the fact that small ~sel warning icon may remind tree view disclosure element is not a significant issue since it's not always in focus.

**Comment by vancura** [comment] 2018-06-22 07:10
Let me explain in more detail:

The fact that we're using small icons for errors/warnings in the list helps visibility and level of eye strain – large icons would be too heavy, and the list would be jam-packed. The problem is precisely what you can see above: when an icon is selected it's white (as the expand/collapse chevron), but as it doesn't contain the exclamation glyph it _reminds_ the chevron (it's just upside down).

I think this problem is still just a minor complication and the perk of using small warning/error icons is more important than to change all icons to regular large ones.

**Comment by vancura** [comment] 2018-06-22 07:11
Closing. If you don't agree, please contact us on our real-time channel.

**Closed by vancura** 2018-06-22 07:11 UTC
Labels: Area: Structured Build Output, vs-sync
