### ISSUE TITLE
Regression, text editor behavior

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#4396] opened 2018-03-30 02:25 UTC
When I create a function, I write "static void Open () NEWLINE OPEN BRACE, CLOSE BRACE, UP ARROW, NEWLINE".

Now, when I insert the NEWLINE, instead of getting a newline and an indentation, the character "}" is inserted.  If I type anything it vanishes, and indents and then I can type.    If I try removing it, other selection oddities take place.

Attached is a demo

![2018-03-29 22_23_32](https://user-images.githubusercontent.com/36863/38121896-ffcdb20e-339f-11e8-8ed1-7cfc05a51e9b.gif)

Version details on the disclosure button below:

<details>
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 933)
Installation UUID: 8956d53d-443d-454e-8cf3-e11cbc219f06
Runtime:
	Mono 5.10.0.179 (2017-12/dac60775616) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510000179

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.0.1
	1.0.0
	1.0.0-rc2-3002702
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.0-preview3-004056
	1.0.0-preview2-003121
	1.0.0-preview1-002702
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Android ===

Version: 8.3.0.5 (Visual Studio Community)
Android SDK: /Users/miguel/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 21.1.2

Java SDK: /usr
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.4.0.31 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.0.32 (Visual Studio Community)
Hash: 4d8c4e32
Branch: d15-7
Build date: 2018-03-07 18:39:46-0500

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705000933
Git revision: ace1e107c88477db1abe5e807809650f064112c4
Build date: 2018-03-19 17:42:41-04
Xamarin addins: a01263bdbba2589b1f6e42ef085bd31f6e3bfcf4
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

AddinMaker 1.4.2
MSBuild Editor 2.0.1
xUnit.NET 2 testing framework support 0.7.5
Internet of Things (IoT) development (Preview) 7.1

</details>

**Comment by mrward** [comment] 2018-03-30 07:46
Duplicate of #4346

**Closed by mrward** 2018-03-30 07:46 UTC
