### ISSUE TITLE
Dogfood - trouble with the editor

### ISSUE THREAD

**Issue by migueldeicaza** [mono/monodevelop#6816] opened 2019-01-04 21:33 UTC
Today while I was dogfooding the upcoming 8.0 release, I ran into various editing annoyances, they can all be reproduced by checking out the project I used for dogfooding:

https://github.com/migueldeicaza/FuchsiaSharp

First issue:

* Attempt to add a new line to the comments at the top in Core.cs, rather than having the "//" appear on the first column, just like anything else, they are automatically indented by a tab.

* Adding enumerations does not indent values properly, go to the end of the file in Core.cs, and attempt to add this definition:

```
public enum Foo : uint {
		foo = 1,
                 bar = 2
```

You will notice that bar is indented at the same place that `public` is, rather than being aligned with `foo`.

The C# Code Formating style that I use is `Mono`

> VS bug [#761098](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761098)

**Comment by migueldeicaza** [comment] 2019-01-07 17:24
This is fairly obnoxious as well while editing enums and documentation.   It seems like the documentation can eventually be reformatted (something triggers it if I paste docs), but by default, it is always miss-aligned.   For example:

```
                /// <summary>
                /// Hello_
                /// </summary>
```

In the above, the cursor is here `_`, and if I press return, it renders like this:

```
                /// <summary>
                /// Hello_
        ///
                /// </summary>
```

**Comment by mkrueger** [comment] 2019-01-10 11:47
Duplicate of #6788 - indentation engine got messed up a bit as side effect of a former bug fix. It's already fixed. PR pending.

**Comment by migueldeicaza** [comment] 2019-01-10 15:53
Are we getting this backported to all branches?

**Comment by migueldeicaza** [comment] 2019-01-17 03:33
I checked again with the internal preview Version 7.8 Preview (7.8 build 1547) and it still happens.

**Comment by migueldeicaza** [comment] 2019-01-17 03:43
Ok, this looks addressed in Build 1551

**Closed** 2019-02-07 06:25 UTC
Labels: Area: Text Editor, high-priority, vs-sync
