### ISSUE TITLE
Assembly not found for Android 7.1 support

### ISSUE THREAD

**Issue by jonathanpeppers** [mono/monodevelop#5190] opened 2018-06-25 21:37 UTC
_From @ghuntley on April 19, 2018 5:34_

Howdy,

I'm not blocked but here are some product feedback thoughts going through my brain...

<img width="321" alt="screen shot 2018-04-19 at 3 26 43 pm" src="https://user-images.githubusercontent.com/127353/38973005-0eda2014-43e7-11e8-9fee-4fdd4a776df0.png">

- Why is this error being displayed?
- Should I care?
- The app works at API23 (x86 simulator) so why am I being told this?
- Should I be worried? it's red, has crosses and those are msft/system assemblies.
- I wonder what newbies would think?

### Steps to Reproduce

https://gist.github.com/ghuntley/8834ccf4894a31d1dbb264821d425626

### Version Information

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: a32bd9d1-8328-4615-8629-3d85d971cc40
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Enterprise)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/ghuntley/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

LiveXAML 1.3.31
MFractor 3.05.00
Internet of Things (IoT) development (Preview) 7.1

```

_Copied from original issue: xamarin/xamarin-android#1579_

> VS bug [#640603](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/640603)

**Comment by jonathanpeppers** [comment] 2018-06-25 21:37
_From @mikehachen on May 21, 2018 19:38_

I have the same issue here. Do I need to worry? Red crosses always give me bad feelings...

**Comment by jonathanpeppers** [comment] 2018-06-25 21:37
_From @mikehachen on May 31, 2018 20:26_

Any news? I have some problems with my app (crashes right after startup) but I don't know if it is related this "error" or something different...

**Comment by slluis** [comment] 2018-06-26 13:48
@sgmunn thoguhts?

**Comment by jonathanpeppers** [comment] 2018-06-27 20:29
@mikehachen can you post a new issue for what you are experiencing? https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests

@sgmunn I think the OP here is mainly posting about the red X's in the screenshot.

**Comment by sgmunn** [comment] 2018-06-27 20:35
yes, for the red X's I do not have a suggestion to what is causing that right now.

**Comment by jonathanpeppers** [comment] 2018-06-27 20:39
So I think these are `Facade` assemblies @sgmunn 

Does there just need to be some additional logic to locate them? They are in `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/Facades/` on my machine.

**Comment by mikehachen** [comment] 2018-06-28 19:41
In the meantime I was able to fix the problem which was causing the app to crash. However those red X's are still there. What do you need to locate the root problem? I moved a second app from pcl to netstandard 2.0 and there I have the same problems. red X's saying that those libs can't be found...

**Comment by sgmunn** [comment] 2018-06-29 15:01
@jonathanpeppers @jonpryor @slluis I've debugged a little and from what I saw it looks like monodevelop is looking in

```
/Library/Frameworks/Mono.framework/External/xbuild-frameworks/../../../Xamarin.Android.framework/Libraries/xbuild-frameworks/MonoAndroid/v1.0
```

to find the android assemblies. The assemblies marked with red x's above are not in this folder. Should they be? Should monodevelop be looking elsewhere as well?

**Comment by ghuntley** [comment] 2018-08-06 12:45
> re: I think the OP here is mainly posting about the red X's in the screenshot.

Correct.

**Comment by mikehachen** [comment] 2018-09-07 06:30
Why is this closed? What is the solution??

**Comment by slluis** [comment] 2018-09-07 07:27
This was closed by mistake.

**Comment by mikebluestein** [comment] 2019-04-04 14:44
I am running this exact issue in VS2017 Mac after installing VS2019 Mac. Is there any way to fix this?

**Comment by KevinSkipRollins** [comment] 2019-04-04 16:46
I too am running into this exact issue after upgrading my Visual Studio for Mac. Claims assemblies not found for framework Xamarin.Android v9.0 support. But I can still build and run the application successfully. Is there any fix for this?

**Comment by karak** [comment] 2019-04-05 00:54
I have met this issue just after I installed VS2019 for Mac.
Any fix? What is caused by this?

**Comment by LawtrustDevelopment** [comment] 2019-04-05 07:10
@karak exact thing happened to me after updating to latest VS version. Very frustrating...

**Comment by Dev1994** [comment] 2019-04-05 07:13
Any solution yet? I've completely uninstalled and reinstalled VS and Xamarin off my machine and still facing the same problem.

**Comment by aspnetde** [comment] 2019-04-05 09:04
Same here 👎

**Comment by hackzai** [comment] 2019-04-05 11:29
same here...

**Comment by Therzok** [comment] 2019-04-05 11:45
There's a fix for this underway in https://github.com/xamarin/xamarin-android/pull/2928

**Closed** 2019-04-05 18:04 UTC
Labels: vs-sync
