### ISSUE TITLE
Loading documents is delayed by 1.5 seconds due to syntax schemes

### ISSUE THREAD

**Issue by Therzok** [mono/monodevelop#4364] opened 2018-03-29 10:03 UTC
We eagerly preload all the syntax highlighting styles, even though we do not use all of them:
```
1.42%   TextEditorDisplayBinding..cctor  •  1,267 ms  •  1 call  •  MonoDevelop.Ide.Editor.TextEditorDisplayBinding..cctor
  1.42%   InitSourceEditor  •  1,267 ms  •  1 call  •  MonoDevelop.Ide.Editor.TextEditorDisplayBinding.InitSourceEditor
    1.42%   LoadCustomStylesAndModes  •  1,263 ms  •  1 call  •  MonoDevelop.Ide.Editor.TextEditorDisplayBinding.LoadCustomStylesAndModes
      1.42%   SyntaxHighlightingService..cctor  •  1,262 ms  •  1 call  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService..cctor
        1.20%   LoadStylesAndModes  •  1,065 ms  •  2 calls  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService.LoadStylesAndModes(Assembly)
          ►1.19%   LoadFile  •  1,060 ms  •  2,842 calls  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService.LoadFile(LanguageBundle, String, Func[Stream], Func[IStreamProvider])
          ►0.00%   SyntaxHighlightingService+<>c__DisplayClass31_1..ctor  •  1 ms  •  2,842 calls  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService+<>c__DisplayClass31_1..ctor
           0.00%   GetManifestResourceNames  •  0 ms  •  2 calls  •  System.Reflection.RuntimeAssembly.GetManifestResourceNames
           0.00%   CtorClosed  •  0 ms  •  5,684 calls  •  System.MulticastDelegate.CtorClosed(Object, IntPtr)
          ►0.00%   OnAssemblyLoadEvent  •  0 ms  •  1 call  •  System.AppDomain.OnAssemblyLoadEvent(RuntimeAssembly)
          ►0.00%   SyntaxHighlightingService+<>c__DisplayClass31_0..ctor  •  0 ms  •  2 calls  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService+<>c__DisplayClass31_0..ctor
        ►0.22%   PrepareMatches  •  195 ms  •  1 call  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService.PrepareMatches
        ►0.00%   AddExtensionNodeHandler  •  0 ms  •  1 call  •  Mono.Addins.AddinManager.AddExtensionNodeHandler(String, ExtensionNodeEventHandler)
        ►0.00%   FirstOrDefault  •  0 ms  •  1 call  •  System.Linq.Enumerable.FirstOrDefault(IEnumerable[TSource], Func[TSourceBoolean])
         0.00%   Regex..ctor  •  0 ms  •  3 calls  •  System.Text.RegularExpressions.Regex..ctor(String)
        ►0.00%   LanguageBundle..ctor  •  0 ms  •  1 call  •  MonoDevelop.Ide.Editor.Highlighting.LanguageBundle..ctor(String, String)
         0.00%   GetFiles  •  0 ms  •  1 call  •  System.IO.Directory.GetFiles(String)
         0.00%   Exists  •  0 ms  •  1 call  •  System.IO.Directory.Exists(String)
         0.00%   GetAssemblies  •  0 ms  •  1 call  •  System.AppDomain.GetAssemblies
        ►0.00%   get_LanguageBundlePath  •  0 ms  •  2 calls  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService.get_LanguageBundlePath
         0.00%   List`1..ctor  •  0 ms  •  1 call  •  System.Collections.Generic.List`1..ctor
         0.00%   CtorOpened  •  0 ms  •  1 call  •  System.MulticastDelegate.CtorOpened(Object, IntPtr, IntPtr)
         0.00%   Add  •  0 ms  •  1 call  •  System.Collections.Generic.List`1.Add(T)
         0.00%   get_CurrentDomain  •  0 ms  •  1 call  •  System.AppDomain.get_CurrentDomain
         0.00%   op_Inequality  •  0 ms  •  1 call  •  System.Reflection.Assembly.op_Inequality(Assembly, Assembly)
         0.00%   get_Assembly  •  0 ms  •  1 call  •  System.RuntimeType.get_Assembly
         0.00%   op_Implicit  •  0 ms  •  2 calls  •  MonoDevelop.Core.FilePath.op_Implicit(FilePath)
         0.00%   CtorClosed  •  0 ms  •  1 call  •  System.MulticastDelegate.CtorClosed(Object, IntPtr)
      ►0.00%   LoadStylesAndModesInPath  •  0 ms  •  1 call  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService.LoadStylesAndModesInPath(String)
       0.00%   Exists  •  0 ms  •  1 call  •  System.IO.Directory.Exists(String)
      ►0.00%   SyntaxHighlightingService+<>c..cctor  •  0 ms  •  1 call  •  MonoDevelop.Ide.Editor.Highlighting.SyntaxHighlightingService+<>c..cctor
      ►0.00%   get_SyntaxModePath  •  0 ms  •  2 calls  •  MonoDevelop.Ide.Editor.TextEditorDisplayBinding.get_SyntaxModePath
       0.00%   op_Implicit  •  0 ms  •  2 calls  •  MonoDevelop.Core.FilePath.op_Implicit(FilePath)
    ►0.00%   DefaultSourceEditorOptions..cctor  •  4 ms  •  1 call  •  MonoDevelop.Ide.Editor.DefaultSourceEditorOptions..cctor
     0.00%   Init  •  0 ms  •  1 call  •  MonoDevelop.Ide.Editor.DefaultSourceEditorOptions.Init
```

We should only load the ones we use.

**Comment by Therzok** [comment] 2018-03-29 10:05
Also, related, we still load the C# theme https://github.com/mono/monodevelop/tree/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/CSharp

**Comment by mkrueger** [comment] 2018-03-29 10:26
duplicate of #3493

**Closed by mkrueger** 2018-03-29 10:26 UTC
