### ISSUE TITLE
Unable to type in text editor when initially loading a solution

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4200] opened 2018-03-16 13:49 UTC
With VS Mac 7.5.0.911 (d15-7) from wrench, opening Main.sln, it is not possible to type into the text editor initially. Eventually you can type into open .cs files. IDE log has the following errors:

```
ERROR [2018-03-16 13:44:58Z]: Error while updating the indentation engine
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.CSharp.Formatting.CSharpTextEditorIndentation.SafeUpdateIndentEngine (System.Int32 offset) [0x00000] in /Users/builder/data/lanes/5965/efcf4643/source/monodevelop/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs:84 
ERROR [2018-03-16 13:44:58Z]: Error in text editor extension chain
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.CSharp.Formatting.CSharpTextEditorIndentation.KeyPress (MonoDevelop.Ide.Editor.Extension.KeyDescriptor descriptor) [0x002c0] in /Users/builder/data/lanes/5965/efcf4643/source/monodevelop/main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs:436 
  at MonoDevelop.Ide.Editor.Extension.TextEditorExtension.KeyPress (MonoDevelop.Ide.Editor.Extension.KeyDescriptor descriptor) [0x00000] in /Users/builder/data/lanes/5965/efcf4643/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TextEditorExtension.cs:83 
  at MonoDevelop.DocFood.DocFoodTextEditorExtension.KeyPress (MonoDevelop.Ide.Editor.Extension.KeyDescriptor descriptor) [0x0000a] in /Users/builder/data/lanes/5965/efcf4643/source/monodevelop/main/src/addins/MonoDevelop.DocFood/MonoDevelop.DocFood/DocFoodTextEditorExtension.cs:59 
  at MonoDevelop.SourceEditor.ExtensibleTextEditor.ExtensionKeyPress (Gdk.Key key, System.UInt32 ch, Gdk.ModifierType state) [0x0003a] in /Users/builder/data/lanes/5965/efcf4643/source/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs:282 
```

> VS bug [#584871](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/584871)

**Comment by Therzok** [comment] 2018-03-16 15:46
Other than fixing the exception, we should also figure out a smart way to not fail the whole extension chain if one extension fails.

**Comment by mrward** [comment] 2018-03-16 18:36
Also happens in older VS Mac 7.5.0.856 (d15-7) just did not notice it there.

**Comment by mkrueger** [comment] 2018-03-19 11:03
Duplicate of #4173

**Closed by mkrueger** 2018-03-19 11:03 UTC
Labels: Area: Text Editor, high-priority, vs-sync
