### ISSUE TITLE
Can't edit csproj (7.7 build 1650)

### ISSUE THREAD

**Issue by StephaneDelcroix** [mono/monodevelop#6406] opened 2018-10-19 08:27 UTC
On this (dogfood) version of VSMac, I can't `Tools->Edit file` a project anymore, and get a 
> Could not load file or assembly 'NuGet.Frameworks, Version=4.3.1.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/313003/47206694-921aa480-d389-11e8-8029-82f2909460ef.png">

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 1650)
Installation UUID: 432670e0-72c2-49ad-9697-54e2fbd0e94c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000190

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.190 (2018-06/226e91a0644) (64-bit)
	Package version: 516000190

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.1
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.2.1.9 (Visual Studio Enterprise)
Hash: 62840955
Branch: 
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.iOS ===

Version: 12.2.1.9 (Visual Studio Enterprise)
Hash: 62840955
Branch: d15-9
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.Android ===

Version: 9.1.0.37 (Visual Studio Enterprise)
Android SDK: /Users/sdx/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4.87 (API level 20)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.0

Java SDK: /Users/sdx/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: dd6b1cc3

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707001650
Git revision: 913c112b500e3e6e6e85c7c15b2d642dc8a82a88
Build date: 2018-10-16 15:55:50+00
Build branch: release-7.7
Xamarin extensions: 9c0205579de8c1ffbc8a481bef699c7aa9315c4f

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Sun Oct  7 14:21:57 PDT 2018
    root:xnu-4903.221.2~12/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DotNetCoreSupportAnyTargetFramework 1.0
MSBuild Editor 2.0.4
NuGet Package Management Extensions 0.13
Show in Github 1.0.4

**Comment by mrward** [comment] 2018-10-19 08:35
@Therzok - This looks like the binding redirect problem you have fixed - #6379

**Comment by Therzok** [comment] 2018-10-19 09:50
Yup

**Comment by mrward** [comment] 2018-10-19 09:52
Going to mark this as a duplicate of #6378

**Closed by mrward** 2018-10-19 09:52 UTC
