### ISSUE TITLE
Can't right click items in the Version Control file list anymore

### ISSUE THREAD

**Issue by nddipiazza** [mono/monodevelop#4835] opened 2018-05-17 05:15 UTC
regression: 

version 7.5 build 1255

steps to reproduce: 

Linux 64-bit any distro. Ubuntu 17.x for example

1. have everything installed `sudo apt install mono-devel nuget monodevelop monodevelop-versioncontrol`
1. make some changes to a git project in monodevelop.
1. open "review changes and commit" menu
2. right click and attempt to "diff". right clicking deselects the object making the context menu in this view unusable.

https://youtu.be/9NpbOErJhqU

This worked in 7.1

> VS bug [#617834](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617834)

**Comment by DavidKarlas** [comment] 2018-05-17 10:51
I can reproduce this also on Mac, I'm setting this to low priority since everything is still functional and works as expected(even if user select multiple files), just visually files get deselected which shouldn't in case of right clicking.

**Comment by nddipiazza** [comment] 2018-05-17 13:28
@DavidKarlas not on linux. you can't get to the right click menu at all and therefore cannot get to the changes unless you go to the file's changes tab.

**Comment by Therzok** [comment] 2018-07-12 17:45
Fixed via https://github.com/mono/monodevelop/pull/5318

**Closed by Therzok** 2018-07-12 17:45 UTC
Labels: Area: Version Control, low-priority, vs-sync
