### ISSUE TITLE
international text is rendered incompletely due to baseline mismatch.

### ISSUE THREAD

**Issue by atsushieno** [mono/monodevelop#4467] opened 2018-04-07 06:17 UTC
The text editor renders text in weird way when there are certain kind of characters on the line.

See this example screenshot:

![image](https://user-images.githubusercontent.com/53929/38452013-a92c5d06-3a75-11e8-8d07-2844b83444e4.png)

Line 1 is rendered appropriately, but line 2 is "broken" in the middle around the baseline (you can see the incomplete alphabets too on the line).

It reproduces regardless of the text editor font size.

It occurs on Ubuntu 17.10. Not sure about other platforms. Checked with 8e82e9f.

> VS bug [#596558](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596558)

**Comment by mkrueger** [comment] 2018-04-09 05:26
I would need a file with these chars.

**Comment by atsushieno** [comment] 2018-04-09 05:34
Looks like Japanese Kana is not enough to reproduce the issue. These are with CJK ideographs to reproduce the issue. Save these lines to any file:

    A
    A漢字
    A

**Comment by mkrueger** [comment] 2018-07-12 11:22
Will have to wait until the new editor is ready. I think that's caused by the switch to harfbuzz in pango on linux.

It would basically force me to implement a proper model layer for layout lines - we'll get all that when taking the vs.net data structures.
But atm I can't justify that work in the old editor since the new one is around the corner. 

So closing that as a wontfix :/.

**Closed by mkrueger** 2018-07-12 11:22 UTC
Labels: Area: Text Editor, linux, vs-sync
