### ISSUE TITLE
Offline NuGet restore fails

### ISSUE THREAD

**Issue by dansiegel** [mono/monodevelop#4052] opened 2018-03-05 23:48 UTC
# Description

When restoring a project while offline the NuGet package restore fails even when the packages exist as part of the local NuGet cache (i.e. the solution has previously been restored while online). 

## Expected 

NuGet should restore using the NuGet cache while offline

## Actual

NuGet restore fails due to inability to reach NuGet sources

> VS bug #578000

**Comment by mrward** [comment] 2018-03-06 09:08
Do you have an example project that reproduces this?

**Comment by dansiegel** [comment] 2018-03-06 19:38
Sure heres a sample app that successfully restores while online, however if I delete my outputs, go offline and restore it fails (although all of the NuGet's are already cached in `/Users/{my user}/.nuget/packages/`)
[Hello.World.zip](https://github.com/mono/monodevelop/files/1786419/Hello.World.zip)

**Comment by mrward** [comment] 2018-03-07 10:56
Thanks. So the .NET Standard, iOS and Android projects all restore offline successfully. The UITest project fails to restore.

It seems that NuGet wants to go online when restoring the UITest project when using Visual Studio for Mac.

```
Restoring packages for Hello.World/tests/Hello.World.UITests/Hello.World.UITests.csproj...
Restoring packages for .NETFramework,Version=v4.6.1...
  GET https://api.nuget.org/v3-flatcontainer/nunit/index.json
  GET https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/nunit/index.json'.
An error occurred while sending the request
  Error: NameResolutionFailure
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json'.
An error occurred while sending the request
  Error: ConnectFailure (Network is unreachable)
  Network is unreachable
  GET https://api.nuget.org/v3-flatcontainer/nunit/index.json
  GET https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/nunit/index.json'.
An error occurred while sending the request
  Error: ConnectFailure (Network is unreachable)
  Network is unreachable
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json'.
An error occurred while sending the request
  Error: ConnectFailure (Network is unreachable)
  Network is unreachable
  GET https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json
  GET https://api.nuget.org/v3-flatcontainer/nunit/index.json
Failed to retrieve information about 'Xamarin.UITest' from remote source 'https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json'.
```

Using nuget from the command line or msbuild /t:restore and they restore OK when offline. They seem to also try to go to a nuget.org url but it looks like they get the index.json from a cache. The urls are prefixed with `CACHE`. I am assuming it is using the local http cache being used. So there is something Visual Studio Mac is doing differently compared with nuget on the command line and presumably Visual Studio on Windows.

nuget command line output:

```
  Restoring packages for Hello.World/tests/Hello.World.UITests/Hello.World.UITests.csproj...
    CACHE https://api.nuget.org/v3-flatcontainer/nunit/index.json
    CACHE https://api.nuget.org/v3-flatcontainer/xamarin.uitest/index.json
```

**Comment by mrward** [comment] 2018-09-27 15:47
Looking at this the only difference I can see between VS Mac and VS 2017 on Windows is they use the default 30 minute timeout for the http-cache.

If you clear out the http-cache `nuget locals http-cache -clear` and try to restore the project (without any existing obj/project.assets.json files) then it will fail from the command line with msbuild /t:restore.

If a restore has worked successfully once with VS Mac, so the project.assets.json files are created, then the restore will no longer fail in VS Mac 7.6 since this now supports doing a no-op restore. I can re-open the solution with internet access disabled, and the restore is a no-op and does not fail.

If the project.assets.json files are deleted then the restore will fail here but that is due to the wildcards being used in the project. This would fail in VS on Windows too if the http-cache was out of date. So I am going to close this since VS Mac 7.6 now supports offline no-op restores.

**Closed by mrward** 2018-09-27 15:47 UTC
Labels: Area: NuGet, vs-sync
