### ISSUE TITLE
UpdateService.cs:581 Updater token could not be retrieved

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5664] opened 2018-08-10 18:05 UTC
Found in the logs for (7.7 build 805)

```
INFO [2018-08-09 12:39:32Z]: Checking for updates: https://software.xamarin.com/Service/Updates?v=2&m=27e1cd61-8f94-4e36-8a49-3211549b6bd0&pv34937104-97FC-42A0-9159-D951135F72CA=707000805&pv88DE1F16-3942-4EF0-A123-F542E1950A10=8&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=512000298&pv4BBD2407-C3ED-4D32-B8CB-0559C7610697=1006003444&pv42a8c70f-b3dc-42f4-b8a5-435a1bb2410c=1531171025&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=2040600011&pv4569c276-1397-4adb-9485-82a7696df22e=2111400011&pvd1ec039f-f3db-468b-a508-896d7c382999=1531862560&pvc07628e8-5521-4c1a-aa3a-f860e664f0a9=2013010000&level=Alpha&os=osx-10.13.6&env=MonoTouchInstalled,MonoDroidInstalled,iphsdk11.4
ERROR [2018-08-09 12:39:32Z]: Updater token could not be retrieved
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Ide.Updater.UpdateService+<GetDefaultUserToken>d__61.MoveNext () [0x00019] in /Users/vsts/agent/2.138.4/work/1/s/md-addins/Xamarin.Ide/Xamarin.Ide/Xamarin.Ide.Updater/UpdateService.cs:581 

```

> VS bug [#662540](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/662540)

**Comment by nosami** [comment] 2018-12-06 09:01
Dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740202

**Closed by nosami** 2018-12-06 09:01 UTC
Labels: Area: IDE Platform, vs-sync
