### ISSUE TITLE
Unable to type space characters into an xml file

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5533] opened 2018-07-28 13:07 UTC
VS Mac 7.6.0.2109
Git revision: 5dae5cd7a9bb6cf438d02a3808337e000cfefab1
Build date: 2018-07-26 14:39:08+00
Build branch: release-7.6
Xamarin extensions: 47dc531ce198dad795623229f3f92e2cf53ab7ef

Enabled user installed extensions
FileNesting 0.1.1
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.13
UIThreadHangAddin 1.0

Open any xml file or create a new one and then you cannot type in space characters. In the screencast below tabs work but when I try to type in more than one space on the empty line nothing happens.

![unabletotypespaces2](https://user-images.githubusercontent.com/372361/43356751-a0f50c22-926e-11e8-8ced-a4cc6036eb94.gif)

I see the same behaviour when creating a new XML file.

No errors in the IDE log.

The Code Formatting settings are configured for XML to not convert tabs to spaces. Changing it to convert tabs to spaces for the current solution does not fix the problem. It allows you to press tab and enter four spaces but you cannot type in two spaces on an empty line.

> VS bug [#655574](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/655574)

**Comment by DavidKarlas** [comment] 2018-08-10 05:48
This regression is caused by https://github.com/mono/monodevelop/pull/5043

**Comment by xamarin-release-manager** [comment] 2018-08-13 16:04
Fixed in version 7.8.0.75 (master)

Pull Request #5645 merged by: Lluis Sanchez
Author: mono
Commit: 2db5b2074c45b7b1f61ff653763cde1c246d8b38 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment] 2018-08-13 16:09
Fixed in version 7.6.0.2173 (release-7.6)

Pull Request #5646 merged by: Lluis Sanchez
Author: mono
Commit: cfd1fa374d03a8f5f1ceceb743b1ad90965e48be (mono/monodevelop)

**Closed by xamarin-release-manager** 2018-08-13 16:09 UTC
Labels: Area: Text Editor, regression, vs-sync

**Comment by xamarin-release-manager** [comment] 2018-08-13 16:10
Fixed in version 7.7.0.828 (release-7.7)

Pull Request #5652 merged by: Lluis Sanchez
Author: mono
Commit: fc47dfbee52123080bb4f38d1020648a42adb7e1 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment] 2018-08-15 08:53
Fixed in version 7.8.0.126 (release-7.7)

Pull Request #5645 merged by: Lluis Sanchez
Author: mono
Commit: 2db5b2074c45b7b1f61ff653763cde1c246d8b38 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment] 2018-08-15 11:55
Fixed in version 7.7.0.931 (release-7.7)

Pull Request #5645 merged by: Lluis Sanchez
Author: mono
Commit: 2db5b2074c45b7b1f61ff653763cde1c246d8b38 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment] 2020-01-22 13:26
Fixed in version 8.6.0.802 (master)

Pull Request #5645 merged by: Lluis Sanchez
Author: mono
Commit: 2db5b2074c45b7b1f61ff653763cde1c246d8b38 (xamarin/monodevelop)
