### ISSUE TITLE
Unit test markers fail silently

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3472] opened 2017-12-05 22:08 UTC
When unit test markers fail to run, they fail silently.

1. Open a project where the unit tests fail to load, e.g. https://github.com/mhutch/MonoDevelop.MSBuildEditor
2. Enable unit test markers
3. Open one of the test classes
4. The test margin markers are visible, even though the load failed
5. Try running one of the tests via the markers. Nothing happens.

I would expect the marker to change to display an error icon with a tooltip if the load has failed, or at least do this when it fails to run.

**Comment by raghorteprasad** [comment] 2018-02-07 12:05
Below is my understanding for expected result kindly correct me if I misunderstood anything 

Steps performed : - Opened a project https://github.com/mhutch/MonoDevelop.MSBuildEditor in VSFM, where MonoDevelop.MSBuildEditor fail to load in Solution explorer showing an error icon with tooltip message saying Load failed: Unknown solution item type:
Also I have observed that in Unit Test Explorer we are getting loading error "The operation failed due to an internal error: Has no Test Fixture". This is observed for QualityAssurance repo.

Please refer the attached screenshots zip file - http://www.screencast.com/users/v-swgang/folders/Default/media/c39da6aa-297b-4d3f-a586-a4c8f50c7a92

So could you please confirm the reproduction steps and our understanding.

**Comment by mhutch** [comment] 2018-02-08 14:55
Do you have AddinMaker extension installed from the extension gallery?

**Comment by raghorteprasad** [comment] 2018-02-09 12:46
VSMac About Info- https://gist.github.com/raghorteprasad/048b872be8066b54cd322b8bfbce2382

Build Version -
Visual Studio Enterprise 2017 for Mac (Preview) Version 7.4 Preview (7.4 build 903)
Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
.NET Core Runtime Versions: 2.0.0
Xamarin.Android Version: 8.2.0.12 (Visual Studio Enterprise)
Xcode 9.2 (13772) Build 9C40b
Xamarin.Mac Version: 4.2.0.19 (Visual Studio Enterprise)
Xamarin.iOS Version: 11.8.0.19 (Visual Studio Enterprise)
Operating System Mac OS X 10.12.6

Expected Result - After successful restoring submodules, project is built successful and Unit Tests pad is showing an error icon with tooltip saying- The operation is failed due to an internal error: Could not load file or assembly 'MonoDevelop.MSBuildEditor.Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

Screenshot- http://www.screencast.com/t/wmyInkSqAIZ

**Comment by slluis** [comment] 2018-02-15 09:59
Fixed by https://github.com/mono/monodevelop/pull/3679.

**Closed by slluis** 2018-02-15 09:59 UTC
Labels: Area: Unit Testing

**Comment by xamarin-release-manager** [comment] 2020-01-22 13:20
Fixed in version 8.6.0.802 (master)

Pull Request #3679 merged by: Lluis Sanchez
Author: mono
Commit: 955d2f045ce167dee69097d5d94a9a78412d35c8 (xamarin/monodevelop)
