### ISSUE TITLE
NullReferenceException in CommentTasksProvider.OnWorkspaceItemClosed

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#4942] opened 2018-05-30 01:36 UTC
On MonoDevelop shutdown I see a nullref in CommentTasksProvider.cs line 168:

![image](https://user-images.githubusercontent.com/679326/40693987-2119c746-636f-11e8-8122-d7687cc9ddbc.png)

```
>	MonoDevelop.Ide.Tasks.CommentTasksProvider.OnWorkspaceItemClosed.AnonymousMethod__0 Line 168	C#
 	System.Linq.Enumerable.WhereEnumerableIterator<System.Collections.Generic.KeyValuePair<object, Microsoft.CodeAnalysis.Editor.TodoItemsUpdatedArgs>>.MoveNext Line 149	C#
 	System.Linq.Enumerable.ToDictionary<System.Collections.Generic.KeyValuePair<object, Microsoft.CodeAnalysis.Editor.TodoItemsUpdatedArgs>, object, Microsoft.CodeAnalysis.Editor.TodoItemsUpdatedArgs> Line 969	C#
 	System.Linq.Enumerable.ToDictionary<System.Collections.Generic.KeyValuePair<object, Microsoft.CodeAnalysis.Editor.TodoItemsUpdatedArgs>, object, Microsoft.CodeAnalysis.Editor.TodoItemsUpdatedArgs> Line 961	C#
 	MonoDevelop.Ide.Tasks.CommentTasksProvider.OnWorkspaceItemClosed Line 168	C#
 	MonoDevelop.Ide.RootWorkspace.NotifyItemRemovedGui Line 1058	C#
 	MonoDevelop.Ide.RootWorkspace.NotifyItemRemoved Line 1036	C#
 	MonoDevelop.Ide.RootWorkspaceItemCollection.OnItemsRemoved Line 1429	C#
 	MonoDevelop.Projects.ItemCollection<MonoDevelop.Projects.WorkspaceItem>.RemoveAt Line 143	C#
 	MonoDevelop.Projects.ItemCollection<MonoDevelop.Projects.WorkspaceItem>.Remove Line 132	C#
 	MonoDevelop.Ide.RootWorkspace.Close Line 393	C#
 	MonoDevelop.Ide.Gui.DefaultWorkbench.Close Line 782	C#
 	MonoDevelop.Ide.Gui.Workbench.Close Line 147	C#
 	MonoDevelop.Ide.IdeApp.Exit Line 438	C#
 	MonoDevelop.Ide.Commands.ExitHandler.Run Line 427	C#
 	MonoDevelop.Components.Commands.CommandHandler.Run Line 70	C#
 	MonoDevelop.Components.Commands.CommandHandler.InternalRun Line 39	C#
 	MonoDevelop.Components.Commands.CommandManager.DefaultDispatchCommand Line 1551	C#
 	MonoDevelop.Components.Commands.CommandManager.DispatchCommand Line 1514	C#
 	MonoDevelop.Components.Commands.CommandManager.DispatchCommand Line 1355	C#
 	WindowsPlatform.MainToolbar.TitleMenuItem.OnMenuClicked.AnonymousMethod__9_0 Line 238	C#

```

> VS bug [#623850](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/623850)

**Comment by Therzok** [comment] 2018-05-30 02:02
Interesting, nice catch!

**Comment by Therzok** [comment] 2018-11-14 00:55
Duplicate of internal bug, was already fixed.

**Closed by Therzok** 2018-11-14 00:55 UTC
Labels: Area: C# Binding, vs-sync
